import { prisma } from "../lib/prisma";

const foods = [
  // Staples & Indian Foods
  {
    name: "Roti / Chapati (Whole Wheat)",
    category: "Staples",
    servingSize: 1,
    servingUnit: "roti",
    calories: 104,
    protein: 3.1,
    carbs: 20.4,
    fat: 0.8,
    fiber: 2.8,
    sodium: 110,
    potassium: 120,
    calcium: 15,
    iron: 1.2,
    magnesium: 32,
    zinc: 0.6,
    vitaminB12: 0,
    folate: 14,
  },
  {
    name: "Cooked White Rice",
    category: "Staples",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 206,
    protein: 4.3,
    carbs: 45.0,
    fat: 0.4,
    fiber: 1.2,
    sodium: 2,
    potassium: 55,
    calcium: 16,
    iron: 1.9,
    magnesium: 19,
    zinc: 0.8,
    folate: 90,
  },
  {
    name: "Cooked Brown Rice",
    category: "Staples",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 218,
    protein: 4.5,
    carbs: 45.8,
    fat: 1.6,
    fiber: 3.5,
    sodium: 2,
    potassium: 84,
    calcium: 20,
    iron: 1.0,
    magnesium: 84,
    zinc: 1.2,
    folate: 8,
  },
  {
    name: "Yellow Dal (Tadka / Cooked)",
    category: "Protein",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 180,
    protein: 11.5,
    carbs: 26.0,
    fat: 4.2,
    fiber: 6.8,
    sodium: 340,
    potassium: 360,
    calcium: 42,
    iron: 2.8,
    magnesium: 54,
    zinc: 1.4,
    folate: 110,
  },
  {
    name: "Rajma (Kidney Beans Curry)",
    category: "Protein",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 210,
    protein: 12.0,
    carbs: 32.0,
    fat: 5.0,
    fiber: 8.5,
    sodium: 420,
    potassium: 480,
    calcium: 58,
    iron: 3.4,
    magnesium: 62,
    zinc: 1.6,
    folate: 125,
  },
  {
    name: "Chole (Chickpea Curry)",
    category: "Protein",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 240,
    protein: 11.0,
    carbs: 34.0,
    fat: 7.5,
    fiber: 7.8,
    sodium: 480,
    potassium: 420,
    calcium: 65,
    iron: 3.2,
    magnesium: 58,
    zinc: 1.5,
    folate: 140,
  },
  {
    name: "Paneer (Cottage Cheese)",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    calories: 265,
    protein: 18.3,
    carbs: 3.4,
    fat: 20.8,
    fiber: 0,
    calcium: 480,
    iron: 0.4,
    magnesium: 18,
    zinc: 2.1,
    vitaminA: 210,
    vitaminB12: 0.8,
  },
  {
    name: "Paneer Butter Masala",
    category: "Protein",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 340,
    protein: 14.5,
    carbs: 12.0,
    fat: 26.0,
    fiber: 2.2,
    sodium: 520,
    calcium: 380,
    iron: 1.1,
  },
  {
    name: "Boiled Egg",
    category: "Protein",
    servingSize: 1,
    servingUnit: "piece",
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    fiber: 0,
    sodium: 62,
    potassium: 63,
    calcium: 25,
    iron: 1.0,
    magnesium: 6,
    zinc: 0.6,
    vitaminA: 75,
    vitaminD: 1.1,
    vitaminB12: 0.6,
    folate: 22,
  },
  {
    name: "Egg Omelette (2 eggs with oil & onion)",
    category: "Protein",
    servingSize: 1,
    servingUnit: "serving",
    calories: 210,
    protein: 13.0,
    carbs: 3.5,
    fat: 16.0,
    fiber: 0.5,
    sodium: 220,
    calcium: 55,
    iron: 2.1,
    vitaminD: 2.2,
    vitaminB12: 1.2,
  },
  {
    name: "Grilled Chicken Breast",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    calories: 165,
    protein: 31.0,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sodium: 74,
    potassium: 256,
    iron: 1.0,
    magnesium: 29,
    zinc: 1.0,
    vitaminB12: 0.3,
  },
  {
    name: "Chicken Curry (Indian Style)",
    category: "Protein",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 290,
    protein: 24.0,
    carbs: 8.0,
    fat: 18.0,
    fiber: 1.5,
    sodium: 510,
    iron: 2.2,
    vitaminB12: 0.5,
  },
  {
    name: "Chicken Biryani",
    category: "Protein",
    servingSize: 1,
    servingUnit: "plate",
    calories: 520,
    protein: 28.0,
    carbs: 62.0,
    fat: 18.0,
    fiber: 3.0,
    sodium: 780,
    iron: 2.8,
  },
  
  // Dairy & Drinks
  {
    name: "Curd / Plain Yogurt",
    category: "Dairy",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 120,
    protein: 6.0,
    carbs: 8.0,
    fat: 7.0,
    fiber: 0,
    calcium: 210,
    magnesium: 19,
    zinc: 0.9,
    vitaminA: 60,
    vitaminB12: 0.6,
  },
  {
    name: "Cow Milk (Whole)",
    category: "Dairy",
    servingSize: 1,
    servingUnit: "glass",
    calories: 150,
    protein: 8.0,
    carbs: 12.0,
    fat: 8.0,
    fiber: 0,
    calcium: 290,
    potassium: 320,
    vitaminA: 110,
    vitaminD: 2.5,
    vitaminB12: 1.1,
  },
  {
    name: "Masala Chai (With milk & sugar)",
    category: "Beverages",
    servingSize: 1,
    servingUnit: "cup",
    calories: 90,
    protein: 2.5,
    carbs: 14.0,
    fat: 3.0,
    sugar: 10.0,
    calcium: 90,
  },
  {
    name: "Whey Protein Shake (1 scoop in water)",
    category: "Protein",
    servingSize: 1,
    servingUnit: "glass",
    calories: 120,
    protein: 24.0,
    carbs: 2.5,
    fat: 1.5,
    fiber: 0.5,
    calcium: 140,
    iron: 0.5,
    vitaminB12: 0.5,
  },

  // Fruits & Vegetables
  {
    name: "Banana",
    category: "Fruits",
    servingSize: 1,
    servingUnit: "piece",
    calories: 105,
    protein: 1.3,
    carbs: 27.0,
    fat: 0.3,
    fiber: 3.1,
    sugar: 14.4,
    potassium: 422,
    magnesium: 32,
    vitaminC: 10.3,
    vitaminA: 4,
  },
  {
    name: "Apple",
    category: "Fruits",
    servingSize: 1,
    servingUnit: "piece",
    calories: 95,
    protein: 0.5,
    carbs: 25.0,
    fat: 0.3,
    fiber: 4.4,
    sugar: 19.0,
    potassium: 195,
    vitaminC: 8.4,
  },
  {
    name: "Orange",
    category: "Fruits",
    servingSize: 1,
    servingUnit: "piece",
    calories: 62,
    protein: 1.2,
    carbs: 15.4,
    fat: 0.2,
    fiber: 3.1,
    sugar: 12.0,
    potassium: 237,
    calcium: 52,
    vitaminC: 69.7,
    folate: 29,
  },
  {
    name: "Cooked Spinach (Palak)",
    category: "Vegetables",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 45,
    protein: 5.0,
    carbs: 7.0,
    fat: 0.8,
    fiber: 4.3,
    sodium: 120,
    potassium: 840,
    calcium: 240,
    iron: 6.4,
    magnesium: 150,
    vitaminA: 940,
    vitaminC: 28.0,
    folate: 260,
  },
  {
    name: "Mixed Vegetable Sabzi",
    category: "Vegetables",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 140,
    protein: 3.5,
    carbs: 18.0,
    fat: 6.5,
    fiber: 5.2,
    sodium: 320,
    potassium: 380,
    calcium: 60,
    iron: 1.8,
    vitaminA: 350,
    vitaminC: 32.0,
  },
  {
    name: "Oatmeal (Cooked with milk & nuts)",
    category: "Staples",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 260,
    protein: 10.5,
    carbs: 38.0,
    fat: 8.0,
    fiber: 6.2,
    sugar: 8.0,
    potassium: 310,
    calcium: 180,
    iron: 2.2,
    magnesium: 75,
    zinc: 1.8,
  },
  {
    name: "Almonds",
    category: "Snacks",
    servingSize: 10,
    servingUnit: "piece",
    calories: 70,
    protein: 2.5,
    carbs: 2.5,
    fat: 6.0,
    fiber: 1.5,
    calcium: 32,
    iron: 0.5,
    magnesium: 32,
    vitaminA: 10,
  },
  {
    name: "Peanut Butter",
    category: "Snacks",
    servingSize: 1,
    servingUnit: "tbsp",
    calories: 95,
    protein: 4.0,
    carbs: 3.5,
    fat: 8.0,
    fiber: 1.0,
    sodium: 75,
    magnesium: 25,
    zinc: 0.5,
  }
];

async function main() {
  console.log("Seeding nutrition food items...");
  for (const food of foods) {
    const existing = await prisma.foodItem.findFirst({
      where: { name: food.name },
    });
    if (!existing) {
      await prisma.foodItem.create({
        data: food,
      });
    }
  }
  console.log("Seeding finished successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
